_target_: convnext_tts.models.discriminator.GeneralDiscriminator
discriminators:
  - _target_: convnext_tts.models.discriminator.MultiPeriodDiscriminator
  - _target_: convnext_tts.models.discriminator.MultiResolutionDiscriminator
