train:
  _target_: convnext_tts.datasets.normal.NormalDataset
  df_file: ${...path.train_df_file}
  wav_dir: ${...path.wav_dir}
  cf0_dir: ${...path.cf0_dir}
  vuv_dir: ${...path.vuv_dir}
  to_mel: ${...mel}

valid:
  _target_: convnext_tts.datasets.normal.NormalDataset
  df_file: ${...path.valid_df_file}
  wav_dir: ${...path.wav_dir}
  cf0_dir: ${...path.cf0_dir}
  vuv_dir: ${...path.vuv_dir}
  to_mel: ${...mel}

collator:
  _target_: convnext_tts.datasets.normal.NormalCollator

max_tokens: 3000
